### ISSUE TITLE
Got error while importing cantonesedetect

### ISSUE THREAD

**Issue by indiejoseph** [CanCLID/cantonesedetect#3]
The problem is that the f-string is split across multiple lines without proper continuation. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/bert-vits2/lib/python3.11/site-packages/cantonesedetect/__init__.py", line 1, in <module>
    from .Detector import CantoneseDetector
  File "/opt/conda/envs/bert-vits2/lib/python3.11/site-packages/cantonesedetect/Detector.py", line 12, in <module>
    from .DocumentFeatures import DocumentFeatures
  File "/opt/conda/envs/bert-vits2/lib/python3.11/site-packages/cantonesedetect/DocumentFeatures.py", line 36
    analysis_string = f"------------------------------------\nSplitting quotes: {
                      ^
SyntaxError: unterminated string literal (detected at line 36)
```

**Comment by laubonghaudoi** [comment]
已經合併咗你嘅PR，而家好返未？

**Comment by indiejoseph** [comment]
Ok thanks!
